[alias]
coverage = ["llvm-cov", "nextest", "--no-report", "--output-dir", "./target/coverage"]
coverage_merge = 'llvm-cov --no-run --lcov --output-path ./target/coverage/lcov.info'
coverage_open = 'llvm-cov --no-run --open --output-dir ./target/coverage'
